-- Tabelas de Servidores Federais (SIAPE)
-- Fonte: portaldatransparencia.gov.br/download-de-dados/servidores

DROP TABLE IF EXISTS siape_remuneracao CASCADE;
DROP TABLE IF EXISTS siape_cadastro CASCADE;

CREATE TABLE siape_cadastro (
    id_servidor_portal  TEXT NOT NULL,
    nome                TEXT,
    cpf                 TEXT,
    matricula           TEXT,
    descricao_cargo     TEXT,
    classe_cargo        TEXT,
    referencia_cargo    TEXT,
    padrao_cargo        TEXT,
    nivel_cargo         TEXT,
    sigla_funcao        TEXT,
    nivel_funcao        TEXT,
    funcao              TEXT,
    codigo_atividade    TEXT,
    atividade           TEXT,
    opcao_parcial       TEXT,
    cod_uorg_lotacao    TEXT,
    uorg_lotacao        TEXT,
    cod_org_lotacao     TEXT,
    org_lotacao         TEXT,
    cod_orgsup_lotacao  TEXT,
    orgsup_lotacao      TEXT,
    cod_uorg_exercicio  TEXT,
    uorg_exercicio      TEXT,
    cod_org_exercicio   TEXT,
    org_exercicio       TEXT,
    cod_orgsup_exercicio TEXT,
    orgsup_exercicio    TEXT,
    cod_tipo_vinculo    TEXT,
    tipo_vinculo        TEXT,
    situacao_vinculo    TEXT,
    dt_inicio_afastamento DATE,
    dt_termino_afastamento DATE,
    regime_juridico     TEXT,
    jornada_trabalho    TEXT,
    dt_ingresso_cargofuncao DATE,
    dt_nomeacao_cargofuncao DATE,
    dt_ingresso_orgao   DATE,
    documento_ingresso  TEXT,
    dt_diploma_ingresso TEXT,
    diploma_ingresso_cargofuncao TEXT,
    diploma_ingresso_orgao TEXT,
    diploma_ingresso_servpublico TEXT,
    uf_exercicio        TEXT,
    PRIMARY KEY (id_servidor_portal)
);

CREATE TABLE siape_remuneracao (
    id                  SERIAL PRIMARY KEY,
    ano                 SMALLINT,
    mes                 SMALLINT,
    id_servidor_portal  TEXT NOT NULL,
    cpf                 TEXT,
    nome                TEXT,
    remuneracao_basica_bruta NUMERIC,
    abate_teto          NUMERIC,
    gratificacao_natalina NUMERIC,
    abate_teto_natalina NUMERIC,
    ferias              NUMERIC,
    outras_remuneracoes NUMERIC,
    irrf                NUMERIC,
    pss_rpgs            NUMERIC,
    demais_deducoes     NUMERIC,
    pensao_militar      NUMERIC,
    fundo_saude         NUMERIC,
    taxa_imovel_funcional NUMERIC,
    remuneracao_apos_deducoes NUMERIC,
    verbas_indenizatorias_civil NUMERIC,
    verbas_indenizatorias_militar NUMERIC,
    verbas_desligamento NUMERIC,
    total_verbas_indenizatorias NUMERIC
);
