-- TCE-PB servidor: dedupe + UNIQUE INDEX expression-based
--
-- NK 10 cols: (municipio, codigo_ug, cpf_cnpj, matricula, ano_mes,
--              tipo_cargo, valor_vantagem, descricao_cargo, nome_servidor,
--              data_admissao)
-- Pos cleanup de 23 grupos full-row identical, NK eh unique.
--
-- DEPRECATED (ADR-0014): a NK natural inclui colunas NULLABLE nao-coalescidas
-- (municipio: 90.047 NULL; nome_servidor: 201 NULL em prod 2026-06). UNIQUE
-- INDEX trata NULL como DISTINTO -> ON CONFLICT nao dispara -> re-run do bucket
-- DUPLICARIA. Substituida por synthetic md5 (_nk_md5):
--   * sql/42_tce_pb_synthetic_nk.sql  (coluna + trigger + funcao de hash)
--   * sql/42z_tce_pb_finalize.sql     (dedupe por _nk_md5 + UNIQUE INDEX)
-- No-op intencional (dedupe + index vivem em sql/42z).

-- (sem statements — ver sql/42z_tce_pb_finalize.sql)
